- docs/api-clients/connect-webviews/README.md
- docs/api-clients/connect-webviews/create-a-connect-webview.md
- docs/api-clients/connect-webviews/get-a-connect-webview.md
- docs/api-clients/connect-webviews/list-connect-webviews.md
- docs/api-clients/connected-accounts/README.md
- docs/api-clients/connected-accounts/get-a-connected-account.md
- docs/api-clients/connected-accounts/list-connected-accounts.md
Closes https://github.com/seamapi/api-docs/issues/27
> Document custom metadata

- docs/api-clients/devices/list-unmanaged-devices.md
- docs/api-clients/devices/update-device.md
- docs/api-clients/devices/update-unmanaged-device.md
- Note unmanaging codes when unmanaging a device
- Add note about unmanaging access codes
- Add device update code sample
> Device update code sample

- docs/api-clients/access-codes/create-an-access-code.md
- docs/core-concepts/access-codes.md
Forgot to document, before telling our first customer who might use it.
> Document native scheduling and flag to disable

- docs/seam-components/get-started-with-react-components-and-client-session-tokens.md
- docs/seam-components/make-a-supported-devices-page-with-react.md
- docs/seam-components/react-components.md
- Fix typo
- Fix broken links
- Always link to react.seam.co
- Minor copy updates to seam-components
- Normalize component docs
> Minor fixes to component docs

- docs/SUMMARY.md
- docs/seam-components/angular.md
- docs/seam-components/get-started-with-react-components-and-client-session-tokens.md
- docs/seam-components/make-a-supported-devices-page-with-react.md
- Remove prebuilt term
- Add angular docs
> Angular docs

- docs/device-guides/get-started-with-ecobee-thermostats.md
> fix: javascript example formatting

- docs/api-clients/access-codes/list-unmanaged-access-codes.md
- docs/api-clients/authentication.md
- docs/api-clients/devices/delete-device.md
- docs/api-clients/devices/get-device.md
- docs/api-clients/devices/list-device-providers.md
- docs/api-clients/devices/list-devices.md
- docs/api-clients/devices/list-unmanaged-devices.md
- docs/api-clients/devices/update-device.md
- docs/api-clients/devices/update-unmanaged-device.md
w.r.t. https://github.com/seamapi/api-docs/issues/102
> Update devices client + fix errors reported by customer (Hostvana)

- docs/for-device-manufacturers/creating-a-seam-compatible-door-locks-api/README.md
- docs/for-device-manufacturers/creating-a-seam-compatible-door-locks-api/creating-access-code-crud-endpoints.md
- docs/seam-bridge/connecting-with-doorking.md
I made some changes to the sentences to improve readability
> Documentation

- docs/api-clients/access-codes/README.md
- docs/api-clients/connected-accounts/README.md
- docs/api-clients/devices/README.md
- Add note on multiple errors
- Add multi error or warning note
> Note on additional errors and warnings

- docs/seam-components/react-components.md
- Document connectedAccountIds prop
- Document disableLockUnlock prop
- Document disableFilter prop
> Document new component props

- docs/seam-components/react-components.md
- Fix SupportedDeviceTable props
- Document brands props
> Document brands prop

- docs/api-clients/connected-accounts/README.md
> Add Documentation on `devices_connect_to_other_account`

- north-star-docs/backup-access-codes.md
Closes https://github.com/seamapi/api-docs/issues/129.
> Add guide for backup access codes

- docs/products/smart-locks/access-codes/creating-access-codes.md
- run-snippet-bot.sh
Editorial tweaks + Generate code samples!
> Access Codes Guide -- Create Code -- Generate Code Samples

- docs/products/smart-locks/access-codes/access-code-requirements-for-door-locks.md
- docs/products/smart-locks/access-codes/backup-access-codes.md
- docs/products/smart-locks/access-codes/creating-access-codes.md
- docs/products/smart-locks/access-codes/deleting-access-codes.md
- docs/products/smart-locks/access-codes/lifecycle-of-access-codes.md
- docs/products/smart-locks/access-codes/migrating-existing-access-codes.md
- docs/products/smart-locks/access-codes/modifying-access-codes.md
- docs/products/smart-locks/access-codes/retrieving-access-codes.md
- docs/products/smart-locks/access-codes/troubleshooting-access-code-issues.md
Create better code samples w/ outputs for access code guides
> Access Codes -- More Code Samples

- docs/seam-components/make-a-supported-devices-page-with-react.md
- docs/seam-components/make-a-supported-devices-page.md
- docs/seam-components/react-components/access-code-details.md
- docs/seam-components/react-components/access-code-table.md
- docs/seam-components/react-components/climate-setting-schedule-details.md
- docs/seam-components/react-components/climate-setting-schedule-table.md
- docs/seam-components/react-components/connect-account-button.md
- docs/seam-components/react-components/create-access-code-form.md
- docs/seam-components/react-components/device-details.md
- docs/seam-components/react-components/device-table.md
- docs/seam-components/react-components/supported-devices-table.md
Requires https://github.com/seamapi/react/pull/418
> Update storybook links

- docs/device-guides/sandbox-and-sample-data/README.md
- docs/device-guides/sandbox-and-sample-data/lockly-sample-data.md
Closes https://github.com/seamapi/seam-connect/issues/4435
> feat: add lockly sample data

- docs/README.md
> Removed Device Table

- .gitbook.yaml
- docs/quickstart.md
> Test Redirects of Quickstart

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- snippet-playground/php/.gitignore
- snippet-playground/php/README.md
- snippet-playground/php/composer.json
- snippet-playground/php/main.php
Add a snippet to show the Seam API running in a dev container. Fixes #214
> #214 Add php snippet

- docs/README.md
> Fix H1 for top-level README because GitBook sync did not push this change

- .devcontainer/devcontainer.json
- docs/README.md
- docs/api-clients/installation.md
- docs/device-guides/get-started-with-2n-intercoms.md
- docs/device-guides/get-started-with-august-locks.md
- docs/device-guides/get-started-with-controlbyweb-devices.md
- docs/device-guides/get-started-with-dormakaba-oracode-locks.md
- docs/device-guides/get-started-with-ecobee-thermostats.md
- docs/device-guides/get-started-with-igloo-locks.md
- docs/device-guides/get-started-with-kwikset-wifi-locks.md
- docs/device-guides/get-started-with-minut-sensors.md
- docs/device-guides/get-started-with-noiseaware-sensors.md
- docs/device-guides/get-started-with-nuki-locks.md
- docs/device-guides/get-started-with-salto-locks.md
- docs/device-guides/get-started-with-schlage-locks.md
- docs/device-guides/get-started-with-smartlocks-api.md
- docs/device-guides/get-started-with-ttlock-devices.md
- docs/device-guides/get-started-with-wyze-locks.md
- docs/device-guides/get-started-with-yale-locks.md
- docs/quickstart.md
- docs/seam-components/overview/get-started-with-react-components-and-client-session-tokens.md
We recently got the npm package name `seam`. updating install instructions
> NPM Package Name Update

- .devcontainer/devcontainer.json
- snippet-playground/go/go.mod
- snippet-playground/go/go.sum
You can now successfully execute seam cli commands on fakeseamconnect inside api-docs codespaces
Issue: https://github.com/seamapi/api-docs/issues/228
https://github.com/seamapi/api-docs/assets/41388251/a87d29ca-d34d-484b-8c7b-56b876705d5d
> add seam-cli

- docs/seam-components/overview/getting-started-with-seam-components.md
> fix: Typo for "Vue"

- .devcontainer/Dockerfile
- snippet-playground/python-next/README.md
- snippet-playground/python-next/main.py
@razor-x: It can't possibly be this easy, right?!
> Add python-next to snippet-playground

- snippet-playground/python-next/main.py
Whoops! Forgot to change the import statement in the Python-Next snippet-playground.
Is this correct now, @razor-x? Thanks!
> Fix Python-Next snippet-playground import

- docs/api/acs/systems/README.md
- src/layouts/api-route.hbs
> Remove extra ---

- package-lock.json
- package.json
- src/lib/layout-context.ts
- src/lib/reference.ts
- **Add missing dependencies**
- **Skip generating undocumented endpoints and routes**
- **Do not document undocumented properties**
- **Do not document undocumented parameters**
> Do not documented undocumented things

- docs/api/acs/systems/get.md
- docs/api/acs/systems/list.md
- docs/api/acs/systems/list_compatible_credential_manager_acs_systems.md
- src/data/code-sample-definitions/acs-systems.yaml
Need ideas for how to generate and keep track of unique real-looking resource IDs for these code samples. Thanks!
> Add code samples for acs_systems/get and /list_compatible_credential_manager_acs_systems

- docs/api/acs/systems/get.md
- docs/api/acs/systems/list.md
- docs/api/acs/systems/list_compatible_credential_manager_acs_systems.md
- docs/api/acs/users/add_to_access_group.md
- docs/api/acs/users/create.md
- docs/api/acs/users/delete.md
- docs/api/acs/users/get.md
- docs/api/acs/users/list.md
- docs/api/acs/users/remove_from_access_group.md
- docs/api/acs/users/suspend.md
- docs/api/acs/users/unsuspend.md
- docs/api/acs/users/update.md
- package-lock.json
- package.json
- src/data/code-sample-definitions/acs-users.yaml
- src/lib/format-code.ts
https://hello-seam.slack.com/archives/C07DTP6EGBZ/p1727130931172749
> Adds ACS User  sample requests

- package-lock.json
- package.json
- src/lib/report.ts
- **Bump blueprint to 0.28.3**
- **Remove endpoint dedupe logic from report**
> Bump blueprint to 0.28.3 and remove endpoint dedupe logic from report

- docs/device-and-system-integration-guides/4suites-locks/README.md
- docs/device-and-system-integration-guides/4suites-locks/get-started-with-4suites-locks.md
- docs/device-and-system-integration-guides/akiles-locks/README.md
- docs/device-and-system-integration-guides/akiles-locks/get-started-with-akiles-locks.md
- docs/device-and-system-integration-guides/honeywell-thermostats/README.md
- docs/device-and-system-integration-guides/lockly-locks/README.md
- docs/device-and-system-integration-guides/schlage-locks/README.md
- docs/device-and-system-integration-guides/tedee-locks/README.md
- docs/device-guides/2n-intercom-systems.md
- docs/device-guides/august-locks.md
- docs/device-guides/avigilon-alta-access-system.md
- docs/device-guides/brivo-access.md
- docs/device-guides/dormakaba-oracode-locks.md
- docs/device-guides/ecobee-thermostats.md
- docs/device-guides/get-started-with-august-locks.md
- docs/device-guides/get-started-with-ttlock-devices.md
- docs/device-guides/google-nest-thermostats/README.md
- docs/device-guides/hubitat-elevation-hub.md
- docs/device-guides/igloohome-locks.md
- docs/device-guides/kwikset-locks.md
- docs/device-guides/minut-sensors.md
- docs/device-guides/noiseaware-sensors.md
- docs/device-guides/nuki-locks.md
- docs/device-guides/pti-storlogix-cloud.md
- docs/device-guides/salto-locks.md
- docs/device-guides/ttlock-locks.md
- docs/device-guides/wyze-locks.md
- docs/device-guides/yale-locks.md
- docs/seam-components/react-components/supported-devices-table.md
@razor-x Did I do this PR correctly? Created a branch off of the branch in which I deleted all the supported device tables. Now, in this PR, I'm trying to merge this branch-off-a-branch into main.
> Add links to mkt site

- docs/core-concepts/authentication/api-keys.md
- docs/core-concepts/authentication/personal-access-tokens.md
- docs/core-concepts/webhooks.md
- docs/core-concepts/workspaces/README.md
- docs/device-and-system-integration-guides/4suites-locks/get-started-with-4suites-locks.md
- docs/device-and-system-integration-guides/akiles-locks/get-started-with-akiles-locks.md
- docs/device-guides/get-started-with-august-locks.md
- docs/device-guides/get-started-with-ttlock-devices.md
- docs/go-live.md
- docs/quickstart.md
Linear doc issue to replace these supademos with something that shows the up-to-date Seam Console UI and that works consistently... https://linear.app/seam/issue/DOC-57/re-add-up-to-date-animated-gifs-or-movies-in-place-of-removed
> Remove all supademos because they keep breaking

- docs/api/acs/users/create.md
- docs/api/acs/users/update.md
- docs/api/user_identities/update-a-user-identity.md
- src/data/code-sample-definitions/acs-users.yaml
From: https://hello-seam.slack.com/archives/C05QMFA1140/p1734548845125909
> Fix params for create ACS user code sample

- src/lib/blueprint.ts
- src/lib/format-code.ts
- src/metalsmith.ts
- **Check for ruby and syntax_tree**
- **Add SKIP_CODE_FORMAT override**
> Check for syntax_tree

- src/layouts/api-endpoint.hbs
Splitting this out from https://github.com/seamapi/docs/pull/503
> Render None if no parameters

- docs/api/acs/access_groups/README.md
- docs/api/acs/credentials/README.md
- docs/api/acs/encoders/README.md
- docs/api/acs/entrances/README.md
- docs/api/acs/systems/README.md
- docs/api/acs/users/README.md
- docs/api/phones/README.md
- docs/api/user_identities/enrollment_automations/README.md
- src/layouts/api-route.hbs
Not sure if I added the hr in the correct place...
> Add horizontal line between Endpoints and Events sections

- docs/api/acs/access_groups/README.md
- docs/api/acs/credentials/README.md
- docs/api/acs/encoders/README.md
- docs/api/acs/encoders/encode_credential.md
- docs/api/acs/encoders/scan_credential.md
- docs/api/acs/entrances/README.md
- docs/api/acs/systems/README.md
- docs/api/acs/users/README.md
- docs/api/phones/README.md
- docs/api/thermostats/activate_climate_preset.md
- docs/api/thermostats/cool.md
- docs/api/thermostats/heat.md
- docs/api/thermostats/heat_cool.md
- docs/api/thermostats/off.md
- docs/api/thermostats/schedules/README.md
- docs/api/thermostats/set_fan_mode.md
- docs/api/thermostats/set_hvac_mode.md
- docs/api/user_identities/README.md
- docs/api/user_identities/enrollment_automations/README.md
- src/layouts/api-route.hbs
- src/layouts/partials/api-resource.hbs
- src/layouts/partials/deprecated-warning.hbs
- src/layouts/partials/object-property-details.hbs
- src/layouts/partials/property-details.hbs
- src/lib/handlebars-helpers.ts
- src/lib/layout/api-route.ts
- **Add deprecated warning partial**
- **Add property details partial**
- **Map flattened object blueprint props to route props**
- **Add list properties and list item format**
> Add list properties and list item format

- package-lock.json
- package.json
- src/lib/format-code.ts
- src/lib/layout/api-endpoint.ts
- **Remove php via format hook**
- **Retry ruby format**
> Increase timeout for ruby format

- codegen/lib/layout/api-endpoint.ts
- docs/api/access_grants/create.md
- docs/api/customers/push_data.md
- docs/api/thermostats/daily_programs/create.md
- docs/api/thermostats/daily_programs/update.md
Closes https://linear.app/seam/issue/CX-442/the-requested-access-methods-param-access-grantscreate-is-missing-from
Fix was just to define `objectParameters` as well for list of objects
> fix: missing parameters for Array of Objects

- .eslintrc.json
- .gitignore
- .prettierignore
- LICENSE.txt
- codegen/lib/format-code.ts
- eslint.config.ts
- gitbook-plugin/src/index.tsx
- package-lock.json
- package.json
- tsconfig.json
- **Update to @seamapi/smith with ESLint v10**
- **Update @prettier/plugin-php**
> Update to use ESLint v10
